### ISSUE TITLE
Add NodeJS CI Workflow

### ISSUE THREAD

**Issue by lelouchB** [lelouchB/final-space-api#5]
Relies on #2  i.e. after Tests have been written.

Here is a possible 

```yaml
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
```
